### ISSUE TITLE
Error: Failed building wheel for faulthandler

### ISSUE THREAD

**Issue by bhwein** [bpteague/cytoflow#135]
Error when running pip install cytoflow:
[error.pdf](https://github.com/bpteague/cytoflow/files/1174642/error.pdf)

**Comment by bhwein** [comment]
This seems to be fixed by using command: xcode-select --install to install xcrun on OS X El Capitan and higher.

**Comment by bpteague** [comment]
Two things.  First, this appears to be a bug in `faulthandler`, not `cytoflow` -- I recommend that you file a bug with that project.

And second, I'll be honest, because of the insanity that is the python packaging world, `pip install` support is kind of low-priority.  The recommended way to install is on Anaconda, their packaging setup is much saner (and includes, for example, Qt5 and PyQt5).  

I'll update the wheels in PyPI when I release 1.0 (Real Soon Now), but the docs are all Anaconda-centric -- if you're using `pip`, you're kind of on your own.
