### ISSUE TITLE
horizontal bar plots don't have the right axis tics

### ISSUE THREAD

**Issue by bpteague** [bpteague/cytoflow#141]

**Comment by bpteague** [comment]
fixed

**Comment by NicholasDeLateur** [comment]
Doesn't seem to be fixed in 1.0.0

When making a horizontal bar chart it doesn't swap the axis titles respectively from the defaults

![image](https://user-images.githubusercontent.com/15463085/52285430-4d187f00-2934-11e9-824a-e00dd899229e.png)

[Bar.log](https://github.com/bpteague/cytoflow/files/2832772/Bar.log)
