### ISSUE TITLE
Opening Saved Workspaces in GUI

### ISSUE THREAD

**Issue by jhletendre** [bpteague/cytoflow#147]
Current GUI does not allow re-opening of saved workflows, and does not recognize saved workflows when searching using the 'open' function operating on Windows 10. When opened from their folder directly from 'My Computer'/'This PC', Cytoflow GUI opens but saved work does not appear - it is the same as opening a new workflow. No error code received, the program just does not recognize the saved data.

**Comment by bpteague** [comment]
Thanks for the bug report!  I think this is maybe two issues:
 - When you start the GUI, then click "Open", can you open a previously-saved workflow?  The load/save routines have changed dramatically (for the better!) in the last 9 months.  If you have an issue opening a saved workflow this way with the latest release, please open a new bug.

- Double-clicking on a .flow file in Explorer doesn't work.  Unfortunately, that is operating system integration that Cytoflow doesn't support (mostly because then I would need to support similar integration on MacOS and Linux, as well, and I don't have the bandwidth.)  If you want to, though, you can right-click on a file, then choose "Open with...." and choose Cytoflow.  That should work with the upcoming 1.0 release.
