### ISSUE TITLE
Will not let me draw polygon

### ISSUE THREAD

**Issue by pifreak0679** [bpteague/cytoflow#190]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do? I am trying to draw a polygon gate
  - What happened? It will not let me add points
  - What did you expect to happen? I wanted to make a polygon
[No Polygon.log](https://github.com/bpteague/cytoflow/files/1968574/No.Polygon.log)

  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
Yep, known issue with the development version -- this is what happens when you use pre-release software (-:

If you'd like to try out a version that I think has it fixed, you can download it here:

https://ci.appveyor.com/api/buildjobs/kig4klp4nowilyvd/artifacts/dist%2Fcytoflow-dev-win-amd64.exe

and let me know if it works.  Also, this version can open .flow files with missing .fcs files (-:

**Comment by pifreak0679** [comment]
It still isn't working :/

Alex

**Comment by bpteague** [comment]
I have a good test-case.  New version coming soon...

**Comment by bpteague** [comment]
(ps -- thank you for being my high-DPI tester!)

**Comment by bpteague** [comment]
try this one?
https://ci.appveyor.com/api/buildjobs/4g4n1mbj6dwxhs6q/artifacts/dist%2Fcytoflow-dev-win-amd64.exe

**Comment by pifreak0679** [comment]
Hi Brian!

I don't mind being the tester at all - I really appreciate you fixing it
for me though! It seems to be working much better now!

Thank you!

Alex Pouliot

**Comment by bpteague** [comment]
Great.  I'll close this bug, then -- if it's still an issue in the next release, feel free to re-open.
