### ISSUE TITLE
GUI: TASBE Bleedthrough Plots Not Displaying

### ISSUE THREAD

**Issue by jhletendre** [bpteague/cytoflow#191]
### PLATFORM (Mac, PC, Linux, other):

PC

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):

Windows 10

### SEVERITY (Critical? Major? Minor? Enhancement?):

Minor

### DESCRIPTION:
  - What were you trying to do?

Trying to view channel bleedthrough plots for 3 channels to ensure the data made sense.

  - What happened?

Plots did not display whereas Autofluorescence, Bead Calibration and Color Translation all displayed fine.
Received the following error message:

"Error: AttributeError: '_Undefined' object has no attribute 'inverse'
Location: File "cytoflow/utility/logicle_scale.py", line 404, in transform_non_affine
Thread: MainThread

  - What did you expect to happen?

I expected the plots to display without issue.

**Comment by bpteague** [comment]
(Another helpful thing would be some data files that I can use to reproduce it.)

**Comment by bpteague** [comment]
From the error, it looks like the plots were trying to display using the logicle scale -- which is very, very strange because they're all hard-wired to use a log scale.  I can't reproduce.  If it's a reproducible problem with 1.0 (being released Real Soon Now), please re-open and attach a log file and some example data and I'll have a look.
