### ISSUE TITLE
Error when trying to open jupyter notebook file from GUI

### ISSUE THREAD

**Issue by joagutierrez** [bpteague/cytoflow#218]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
I analyzed my data in a jupyter script and generated plots. I wanted to export my plots to some useful format (in particular, some vector graphic one) but I couldn't find a way to do it, since the view objects could not be saved as matplotlib figures. However, I realized that in the cytoflow GUI there is a way to export figures. I tried to open the jupyter script file with the cytoflow GUI, but I got the following error message: 

Error: <class 'AttributeError'>:'str' object has no attribute 'lock'
Location: File "C:.....\anaconda3\envs\cytoflow\lib\site-packages\cytoflowgui\flow_task.py", line 273, in open_file   wi.lock.acquire()
Thread: Main

I know it is possible to export a workflow performed in the GUI to a jupyter file that can be opened as a notebook. But is it possible to open a jupyter notebook file in the GUI (e.g. to export generated plots into vector graphics)? I think this would be a very useful functionality that would allow to fully combine GUI- and Notebook-based analysis.

Thank you very much in advance and also congratulations on the Cytoflow project, I think it is awesome!
[Bug_NotOpenJupyter.log](https://github.com/bpteague/cytoflow/files/2348090/Bug_NotOpenJupyter.log)

  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
Hi @joagutierrez, thanks for the bug report.  Unfortunately, the GUI --> notebook export is one way:  you can export a notebook but not import one.

I'm happy to hear you're finding the Jupyter notebook interface useful!  Because cytoflow uses matplotlib.pyplot for its figure management, you can save those plots as SVGs or PDFs using matplotlib.pyplot.savefig.  It will let you save as any format that your matplotlib installation supports.  Just make sure to call it from the same cell as you made the plot in (I think.)

I should definitely catch that error, though, and show a more descriptive dialog if the GUI can't open the file.

**Comment by bpteague** [comment]
(the error message is now more informative!  thanks again for the bug report.)
